blank_issues_enabled: false
contact_links:
  - name: Question or discussion
    url: https://github.com/chadeldridge/vsleep/discussions
    about: For questions and general discussion, please use GitHub Discussions rather than opening an issue.
